[BingImagesLarge]
images_xpath = "//img[contains(@class,'mimg')]"
selected_image_xpath = "//img[@class=\"sFlh5c pT0Scc iPVvYb\" and @jsname=\"kn3ccd\"]"
show_more_xpaths = [
    "//a[@class=\"btn_seemore cbtn mBtn\" and @role=\"button\" and @value=\"See more images\"]",
    "//div[@class=\"ra_expandButton\" and @role=\"button\"]",
]
base_search_url = "https://www.bing.com/images/search?q={query}&qft=+filterui:imagesize-large"
close_path = "//a[@data-tooltip=\"Close image\" and @class=\"Close\" and @role=\"Button\"]"
